                    <ul class="icon_socials">
[row:"select * from table3 where string1='[var:"themer_icon_socials_inc"end var]' and md5='plugin_show'","                         
    <li class="ic_facebook ishofrow(string40)"><a target='_blank' href="row(string20)" title="Visit us on Facebook"></a></li>
    <li class="ic_twitter ishofrow(string41)"><a target='_blank' href="row(string21)" title="Follow us on Twitter"></a></li>
    <li class="ic_rss ishofrow(string42)"><a target='_blank' href="row(string22)" title="RSS Feed"></a></li>
    <li class="ic_mail ishofrow(string43)"><a target='_blank' href="mailto:row(string23)" title="Mail"></a></li>
    <li class="ic_plus ishofrow(string44)"><a target='_blank' href="row(string24)" title="Google Plus"></a></li>
    <li class="ic_linkedin ishofrow(string45)"><a target='_blank' href="row(string25)" title="LinkedIn"></a></li>
    <li class="ic_rssmail ishofrow(string46)"><a target='_blank' href="row(string26)" title="RSS Mail"></a></li>
    <li class="ic_skype ishofrow(string47)"><a target='_blank' href="row(string27)" title="Skype"></a></li>     
 "end row]                        
                    </ul>        