                    <div class="search_area">
                        <form method="get" name="s" id="searchform">
                            <input id="text_search" type="text" name="Search" class="s" onfocus="if(this.value=='search...') this.value='';" onblur="if(this.value=='') this.value='search...';" value="search..."/>                                    
                            <input id="submit_search" type="submit" value="" id="searchsubmit" name="btn_search"/>
                            <input type="hidden" value="[setting:"Search_page"end setting]" name="id">
                        </form> 
                    </div>
