<div class = "box statistic" dir="[rtl_ltr]" style="">
    <form method="post">
<label>[Cache page for] [function:"get_cache('CachePageTime')"end function]</label> <br/>
<select name="CachePageTime">
    <option value="1">[No cache Time]</option>
    <option value="60">1 [xMinute]</option>
    <option value="300">5 [xMinute]</option>
    <option value="600">10 [xMinute]</option>
    <option value="1800">30 [xMinute]</option>
    <option value="3600">1 [xHour]</option>
    <option value="7200">2 [xHour]</option>
    <option value="21600">6 [xHour]</option>
    <option value="86400">1 [xDay]</option>
    <option value="604800">7 [xDay]</option>
</select><br><br>

<label>[Cache SQL for] [function:"get_cache('CacheSQLTime')"end function]</label> <br/>
<select name="CacheSQLTime">
    <option value="1">[No cache Time]</option>
    <option value="60">1 [xMinute]</option>
    <option value="300">5 [xMinute]</option>
    <option value="600">10 [xMinute]</option>
    <option value="1800">30 [xMinute]</option>
    <option value="3600">1 [xHour]</option>
    <option value="7200">2 [xHour]</option>
    <option value="21600">6 [xHour]</option>
    <option value="86400">1 [xDay]</option>
    <option value="604800">7 [xDay]</option>
</select><br><br>

<label>[Cache Widget for] [function:"get_cache('CacheFileTime')"end function]</label> <br/>
<select name="CacheFileTime">
    <option value="1">[No cache Time]</option>
    <option value="60">1 [xMinute]</option>
    <option value="300">5 [xMinute]</option>
    <option value="600">10 [xMinute]</option>
    <option value="1800">30 [xMinute]</option>
    <option value="3600">1 [xHour]</option>
    <option value="7200">2 [xHour]</option>
    <option value="21600">6 [xHour]</option>
    <option value="86400">1 [xDay]</option>
    <option value="604800">7 [xDay]</option>
</select><br>


<label>[cachetype1] [function:"get_cache('CachePluginTime1')"end function]</label> <br/>
<select name="CachePluginTime1">
    <option value="1">No cache Time</option>
    <option value="60">1 [xMinute]</option>
    <option value="300">5 [xMinute]</option>
    <option value="600">10 [xMinute]</option>
    <option value="1800">30 [xMinute]</option>
    <option value="3600">1 [xHour]</option>
    <option value="7200">2 [xHour]</option>
    <option value="21600">6 [xHour]</option>
    <option value="86400">1 [xDay]</option>
    <option value="604800">7 [xDay]</option>
</select><br>
<label>[cachetype2] [function:"get_cache('CachePluginTime2')"end function]</label> <br/>
<select name="CachePluginTime2">
    <option value="1">No cache Time</option>
    <option value="60">1 [xMinute]</option>
    <option value="300">5 [xMinute]</option>
    <option value="600">10 [xMinute]</option>
    <option value="1800">30 [xMinute]</option>
    <option value="3600">1 [xHour]</option>
    <option value="7200">2 [xHour]</option>
    <option value="21600">6 [xHour]</option>
    <option value="86400">1 [xDay]</option>
    <option value="604800">7 [xDay]</option>
</select><br>
<label>[cachetype3] [function:"get_cache('CachePluginTime3')"end function]</label> <br/>
<select name="CachePluginTime3">
    <option value="1">No cache Time</option>
    <option value="60">1 [xMinute]</option>
    <option value="300">5 [xMinute]</option>
    <option value="600">10 [xMinute]</option>
    <option value="1800">30 [xMinute]</option>
    <option value="3600">1 [xHour]</option>
    <option value="7200">2 [xHour]</option>
    <option value="21600">6 [xHour]</option>
    <option value="86400">1 [xDay]</option>
    <option value="604800">7 [xDay]</option>
</select><br>
<label>[cachetype4] [function:"get_cache('CachePluginTime4')"end function]</label> <br/>
<select name="CachePluginTime4">
    <option value="1">No cache Time</option>
    <option value="60">1 [xMinute]</option>
    <option value="300">5 [xMinute]</option>
    <option value="600">10 [xMinute]</option>
    <option value="1800">30 [xMinute]</option>
    <option value="3600">1 [xHour]</option>
    <option value="7200">2 [xHour]</option>
    <option value="21600">6 [xHour]</option>
    <option value="86400">1 [xDay]</option>
    <option value="604800">7 [xDay]</option>
</select><br>
<br>


<button type="submit" role="button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" id="button"><span class="ui-button-text">[Save]</span></button>
</form>    

</div>