<div class="wrapper_content">
    <div class="lay_base content_pattern"></div>
    <div class="bar_separate content_separate"></div>
    <div class="lay_base content_shadow"></div>
    <div id="content" class="widget_droppable">
        
[function:"get_widget()"end function]
        
        
        
        
        
        
        
        
    </div>
<br clear="all"/>    
</div>
<div style='display: none'>
[IF:"[var:"_MSG"end var]","
[dialog:"","[var:"_MSGTITLE"end var]","[var:"_MSG"end var]","modal,autoopen","OK:close()"end dialog]
"end IF]
</div>
<iframe name="ajax_sfhati" style="border:0;width:1px;height:1px" id="ajax_sfhati"></iframe>