<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" dir="ltr" lang="en-gb"><head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8"/>        
        <meta name="robots" content="index, follow"/>
        <meta name="keywords" content="[setting:"CEOKeywords"end setting] [this:"page_key"end this] [var:"keywords"end var]"/>

              <meta property="og:title" content="[var:"shear_title"end var]" />
              <meta property="og:description" content="[var:"shear_discription"end var]" />
                  <meta property="og:image" content="[var:"shear_image"end var]" />

                      <meta name="description" content="[setting:"CEODiscription"end setting] [this:"description"end this]"/>
                          <meta name="generator" content="Sfhati! V.[constant:"Version"end constant] - Open Source CMS - Content Management System"/>
                              <meta name="google-site-verification" content="[setting:"google-site-verification"end setting]" />
                                  <title>[setting:"title"end setting] [this:"page_name"end this] [var:"more_title"end var]</title>
                                    <link href="[constant:"TEMPLATE_LINK"end constant]sfhati/images/favicon.png" rel="icon" type="image/png" />
                                    <link rel="apple-touch-icon" href="[constant:"TEMPLATE_LINK"end constant]sfhati/images/favicon.png" />

                                    <link id="css_compressionall" media="screen" href="[var:"css_compression"end var]" type="text/css" rel="stylesheet"/>                    
                                          <link media="screen" id="jquery_uix" href="[setting:"savejqueryui"end setting]" type="text/css" rel="stylesheet"/>
                                          [IF:"[session_var:"IDUSER_ADMIN"end session_var]","
                                          <link id="jquery_ui" media="screen" href="[setting:"savejqueryui"end setting]" type="text/css" rel="stylesheet"/>
                                              "end IF]
                                              <link id="STYLEgroupCSS" nhref="stylecsscode.css" media="screen" href="stylecsscode.css" type="text/css" rel="stylesheet"/>

                                                [var:"_EXTRA_HEADER"end var]
                                                <script type='text/javascript' src='[var:"js_compressionx"end var]'></script>
                                                </head>


                                                <body class="blog">

                                                    [var:"_EXTRA_BODY"end var]          
                                                    [include:"template/panel/panel.inc"end include]            
                                                    <div  class="fullheader_menu_bar">
                                                        <div  class="header_menu_bar">
                                                            <div class="menu-top-bar-container">
                                                                <ul id="menu-top-bar" class="menu">
                                                                    [menu:"menu_top_bar"end menu]
                                                                </ul>
                                                            </div>    
                                                        </div>                
                                                    </div>
                                                    <div class="body_theme" id="body_theme">
                                                        <div class="lay_base body_pattern"></div>
                                                        <div class="global_wrapper">
                                                            <div class="lay_base wrapper_pattern"></div>
                                                            <div id="mobile_wrapper_header" style="display: none">
                                                                <a href="/"><div id="site_logo"></div></a>



                                                                <div class="navbar show_element">
                                                                    <form class="navbar-search">
                                                                        <div class="icon-search icon-white"></div>
                                                                        <input type="text" class="search-query span3" placeholder="Search">
                                                                    </form>           
                                                                    <div class="navbar-inner">
                                                                        <div class="container">
                                                                            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                                                                <span class="icon-bar"></span>
                                                                                <span class="icon-bar"></span>
                                                                                <span class="icon-bar"></span>
                                                                            </a>

                                                                            <div class="nav-collapse">
                                                                                <ul class="nav">
                                                                                    [menu:"header_menu_horisantal"end menu] 
                                                                                </ul>         



                                                                            </div><!-- /.nav-collapse -->
                                                                        </div>
                                                                    </div><!-- /navbar-inner -->
                                                                </div>                                                            
                                                            </div> 




                                                            <div class="wrapper_header"> 
                                                                <div class="clipart">
                                                                    <div class="lay_base header_shine"></div>                
                                                                </div>
                                                                <div class="lay_base header_pattern"></div>
                                                                <div class="lay_base header_shadow"></div>
                                                                <div id="header">
                                                                    <div id="object_wedget_header_mod" class="widget_droppable" style="position: absolute;width:0px;height:0px;">                                        
                                                                        [function:"get_widget(9)"end function]
                                                                    </div>       
                                                                </div>

                                                                <div class="bar_separate header_separate"></div>
                                                            </div>


                                                            <!--header-->              