<style>
    .box,.bxox {
        margin-top: 10px;
        color: #292929;
        border: 1px solid #BABABA;
        background-color: #fff;
        padding: 10px;
        margin: 10px;
        -o-border-radius: 10px;
        -moz-border-radius: 12px;
        -webkit-border-radius: 10px;
        -webkit-box-shadow: 0px 3px 7px #adadad;
        border-radius: 10px;
        -moz-box-sizing: border-box;
        -opera-sizing: border-box;
        -webkit-box-sizing: border-box;
        -khtml-box-sizing: border-box;
        box-sizing: border-box;
        overflow: hidden;
    }   

    .ajaxframeplg H1{ font-size:16px;}
    .ajaxframeplg{ font-size:14px;}

    p.fileformp,.ahoverm{display: block; clear:both;padding: 10px;}
    p.fileformp:hover,.ahoverm:hover{  background-color: #EEEEEE;
                                       border: 1px solid #DDDDDD;}


    p.fileformp input,select,label{display: block}
    .iconpos {
        float: right;
        margin: 5px;
    }
</style>
<div dir='[rtl_ltr]'>
    <span id="result_image"></span>
    [accordion:"accn","collapsible","
    [this widget show in]->

    [function:"getallpagesandtemplatefromwidget([var:"iswidgetcode"end var])"end function]

    ","[this widget not show in]->

    [function:"getallpagesandtemplatefromwidget([var:"iswidgetcode"end var],0)"end function]
    "end accordion]
</div>
