<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" dir="ltr" lang="en-gb"><head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
 
        
        
<script>
    var Main_Domain = '[constant:"Main_Domain"end constant]';
    var SITE_LINK = '[constant:"SITE_LINK"end constant]';
</script>
 <link rel="stylesheet" href="[constant:"TEMPLATE_LINK"end constant]admin/style1.css"></link>   
 <link href="[constant:"TEMPLATE_LINK"end constant]admin/style.css" rel="stylesheet" type="text/css" />
<script type='text/javascript' src='[var:"js_compressionx"end var]'></script>
 
 <style>
    .ui-state-default, .ui-widget-content .ui-state-default {float:left; padding: 2px;margin: 1px;}
</style>
              
    </head>
<body>

    <div style="border: 0;margin:10px;width:auto;" >
[include:"plugin/[var:"plgn"end var]/setting.inc"end include]
</div>


[IF:"[var:"_MSG"end var]","[dialog:"","Message","[var:"_MSG"end var]"end dialog] "end IF]
</body>
</html>