
<span id="result_image"></span>
[IF:"[array:"widget_pro","string2"end array]=themer_icon_socials.inc","
[accordion:"accn","collapsible","
[themer_icon_socials]->
<form action="" id="formslide" enctype="multipart/form-data" method="post" target="x_form">

[input:"text","ic_facebook:[ic_facebook]","[array:"widget_pro","string20"end array]","","inplutsize_large",""end input]
[input:"text","ic_twitter:[ic_twitter]","[array:"widget_pro","string21"end array]","","inplutsize_large",""end input]
[input:"text","ic_rss:[ic_rss]","[array:"widget_pro","string22"end array]","","inplutsize_large",""end input]
[input:"text","ic_mail:[ic_mail]","[array:"widget_pro","string23"end array]","","inplutsize_large",""end input]
[input:"text","ic_plus:[ic_plus]","[array:"widget_pro","string24"end array]","","inplutsize_large",""end input]
[input:"text","ic_linkedin:[ic_linkedin]","[array:"widget_pro","string25"end array]","","inplutsize_large",""end input]
[input:"text","ic_rssmail:[ic_rssmail]","[array:"widget_pro","string26"end array]","","inplutsize_large",""end input]
[input:"text","ic_skype:[ic_skype]","[array:"widget_pro","string27"end array]","","inplutsize_large",""end input]


 <input type="hidden" name="sosaly" id="adsi" value="[var:"iswidgetcode"end var]">
[input:"submit","11x98h","[Send]","","style:"end input]    
</form>
"end accordion]
"end IF]




